FROM maven:3.6-jdk-8
COPY . /ciTest
ENTRYPOINT ["mvn", "-DforkCount=0","-B", "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn","-f","/ciTest/pom.xml","test"]